<?php
// $Id: xoops_version.php,v 1.4 2006/06/08 07:33:05 mikhail Exp $
// ------------------------------------------------------------------------ //
// XOOPS - PHP Content Management System //
// Copyright (c) 2000 xoopscube.org //
// <http://www.xoopscube.org> //
// ------------------------------------------------------------------------ //
// This program is free software; you can redistribute it and/or modify //
// it under the terms of the GNU General Public License as published by //
// the Free Software Foundation; either version 2 of the License, or //
// (at your option) any later version.  //
//   //
// You may not change or alter any portion of this comment or credits //
// of supporting developers from this source code or any supporting //
// source code which is considered copyrighted (c) material of the //
// original comment or credit authors.  //
//   //
// This program is distributed in the hope that it will be useful, //
// but WITHOUT ANY WARRANTY; without even the implied warranty of //
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the //
// GNU General Public License for more details. //
//   //
// You should have received a copy of the GNU General Public License //
// along with this program; if not, write to the Free Software //
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA //
// ------------------------------------------------------------------------ //
$modversion['name'] = _MI_XPLAYER_NAME;
$modversion['version'] = 0.1;
$modversion['description'] = _MI_XPLAYER_DESC;
$modversion['author'] = 'frankblack';
$modversion['credits'] = 'none';
$modversion['help'] = '';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 1;
$modversion['image'] = 'images/xplayer_slogo.png';
$modversion['dirname'] = _MI_XPLAYER_DIRNAME;
// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'xplayer_files';
$modversion['tables'][1] = 'xplayer_player';
// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';
// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _MI_XPLAYER_SUBMIT;
$modversion['sub'][1]['url'] = 'upload.php';
// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'include/search.inc.php';
$modversion['search']['func'] = 'xplayer_search';
// Templates
$modversion['templates'][1]['file'] = 'xplayer_upload.html';
$modversion['templates'][1]['description'] = _MI_XPLAYER_UPLOADER;
$modversion['templates'][2]['file'] = 'xplayer_player.html';
$modversion['templates'][2]['description'] = _MI_XPLAYER_MPEGPLAYER;
$modversion['templates'][3]['file'] = 'xplayer_index.html';
$modversion['templates'][3]['description'] = _MI_XPLAYER_INDEX;
$modversion['templates'][4]['file'] = 'xplayer_category.html';
$modversion['templates'][4]['description'] = _MI_XPLAYER_GENRES;
$modversion['templates'][5]['file'] = 'xplayer_amdelconf.html';
$modversion['templates'][5]['description'] = _MI_XPLAYER_AMDELCONF;
$modversion['templates'][6]['file'] = 'xplayer_ameditgenre.html';
$modversion['templates'][6]['description'] = _MI_XPLAYER_AMEDITGENRE;
$modversion['templates'][7]['file'] = 'xplayer_amgenremanage.html';
$modversion['templates'][7]['description'] = _MI_XPLAYER_AMGENREMANAGE;
$modversion['templates'][8]['file'] = 'xplayer_amplaymanage.html';
$modversion['templates'][8]['description'] = _MI_XPLAYER_AMPLAYMANAGE;
$modversion['templates'][9]['file'] = 'xplayer_amshowmpegs.html';
$modversion['templates'][9]['description'] = _MI_XPLAYER_AMSHOWMPEGS;
$modversion['templates'][10]['file'] = 'xplayer_amxplayer.html';
$modversion['templates'][10]['description'] = _MI_XPLAYER_AMXPLAYER;
$modversion['templates'][11]['file'] = 'xplayer_ameditplay.html';
$modversion['templates'][11]['description'] = _MI_XPLAYER_AMEDITPLAY;
$modversion['templates'][12]['file'] = 'xplayer_ameditmpegs.html';
$modversion['templates'][12]['description'] = _MI_XPLAYER_EDITMPEGS;
// Blocks
$modversion['blocks'][1]['file'] = 'xplayer_blocks.php';
$modversion['blocks'][1]['name'] = _MI_XPLAYER_LATEST;
$modversion['blocks'][1]['description'] = _MI_XPLAYER_LATEST_DESC;
$modversion['blocks'][1]['show_func'] = 'b_xplayer_latest_show';
$modversion['blocks'][1]['edit_func'] = 'b_xplayer_latest_edit';
$modversion['blocks'][1]['options'] = '5';
$modversion['blocks'][1]['template'] = 'xplayer_block_latest.html';
$modversion['blocks'][2]['file'] = 'xplayer_block_scroll.php';
$modversion['blocks'][2]['name'] = _MI_XPLAYER_LATESTSCROLL;
$modversion['blocks'][2]['description'] = _MI_XPLAYER_LATESTSCROLL_DESC;
$modversion['blocks'][2]['show_func'] = 'b_xplayer_latestscroll_show';
$modversion['blocks'][2]['edit_func'] = 'b_xplayer_latestscroll_edit';
$modversion['blocks'][2]['options'] = '5|100';
$modversion['blocks'][2]['template'] = 'xplayer_block_scroll.html';
//Config settings
$modversion['config'][1]['name'] = 'xplayerallowdown';
$modversion['config'][1]['title'] = '_MI_XPLAYER_DOWNLOAD';
$modversion['config'][1]['description'] = '_MI_XPLAYER_ALLOWDOWN';
$modversion['config'][1]['formtype'] = 'yesno';
$modversion['config'][1]['valuetype'] = 'int';
$modversion['config'][1]['default'] = 1;
